modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/OneLousyDev/SimpleFarmWorld/issues"
[[mods]]
modId="simplefarmworld"
version="${file.jarVersion}"
displayName="SimpleFarmWorld"
credits="OneLousyDev"
authors="OneLousyDev"
description='''A mod that adds a farm world dimension. Will be expanded on later.'''
[[dependencies.simplefarmworld]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplefarmworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
